global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sloelux-perfbot'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        target_label: job
        replacement: 'sloelux-perfbot' 